[package]
name = "cim-domain-examples"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
cim-domain = { path = "../.." }
serde_json = "1.0"
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "cim_domain_examples"
path = "src/lib.rs"
